import Head from 'next/head';
import Layout, {siteTitle} from './components/layout';
import utilStyles from '../styles/utils.module.css';

import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/Link';
//need this for analytics,tag manager, other scripts,bot detectors, 
//cookie consent managers,chat support, social media widgets.
import Script from 'next/script'

export default function Home() {
  return (
    <Layout home>
      <Head>
        <title>TECHFLEET</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={utilStyles.headingMd}>
        <p>[Your Self Introduction]</p>
        <p>
          (This is a sample website - you’ll be building a site like this on{' '}
          <a href="https://nextjs.org/learn">our Next.js tutorial</a>.)
        </p>
      </section>
      <div className={styles.main}> 
      <p>daasdfd</p>
      <h1 className="title">
        Read{" "}
        <Link  href='./posts/first-post'>
          <a>first post</a>
        </Link>
        <Link  href='./posts/posts'>
          <a>all posts</a>
        </Link>
      </h1>
          <Image
              src="/images/profile.svg" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
           />
      </div>
        
    </Layout>
  )
}
