import Head from 'next/head';
import Layout, {siteTitle} from './components/layout';
import utilStyles from '../styles/utils.module.css';

import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/Link';
//need this for analytics,tag manager, other scripts,bot detectors, 
//cookie consent managers,chat support, social media widgets.
import Script from 'next/script'
import 'bootstrap/dist/css/bootstrap.min.css';
import MainNavBar from './components/navbar';
import SideNavBar from './components/sidenavbar';

export default function Home() {
  return (
    <Layout home>{/*need to make sure this acts as the container. set the width as 
    variables so that its the same width that rtriggers the other sections
     to be responsice */}
      <Head>
        <title>TECHFLEET</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/*Container */}
      <div className="container">

       {/* navbar */}<MainNavBar/>
       {/* main section*/}<div>
                              {/* left column*/}
                                
                                <SideNavBar/>
                              {/* middle column*/}   
                              {/* right column*/}  
                          </div>
           
           {/* main section*/}
              
      </div>
    </Layout>
  )
}
